-- MySQL Script generated by MySQL Workbench
-- Sat Aug  4 23:28:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tanaytourism
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tanaytourism
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tanaytourism` DEFAULT CHARACTER SET utf8 ;
USE `tanaytourism` ;

-- -----------------------------------------------------
-- Table `tanaytourism`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tanaytourism`.`users` ;

CREATE TABLE IF NOT EXISTS `tanaytourism`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `mid_name` VARCHAR(100) NULL,
  `position` VARCHAR(100) NOT NULL,
  `isLoggedin` INT(1) NOT NULL DEFAULT 0,
  `date_created` DATETIME NOT NULL,
  `date_last_loggedin` DATETIME NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanaytourism`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tanaytourism`.`news` ;

CREATE TABLE IF NOT EXISTS `tanaytourism`.`news` (
  `news_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `slug` VARCHAR(100) NULL,
  `content` TEXT NULL,
  `image_filename` VARCHAR(45) NULL,
  `date_posted` DATETIME NULL,
  `date_updated` DATETIME NULL,
  `date_archived` DATETIME NULL,
  `users_user_id` INT NOT NULL,
  PRIMARY KEY (`news_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanaytourism`.`news_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tanaytourism`.`news_type` ;

CREATE TABLE IF NOT EXISTS `tanaytourism`.`news_type` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(50) NULL,
  `slug` VARCHAR(100) NULL,
  `news_news_id` INT NOT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanaytourism`.`page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tanaytourism`.`page` ;

CREATE TABLE IF NOT EXISTS `tanaytourism`.`page` (
  `page_id` INT NOT NULL AUTO_INCREMENT,
  `page_name` VARCHAR(45) NULL,
  `slug` VARCHAR(100) NULL,
  PRIMARY KEY (`page_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanaytourism`.`gallery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tanaytourism`.`gallery` ;

CREATE TABLE IF NOT EXISTS `tanaytourism`.`gallery` (
  `gallery_id` INT NOT NULL AUTO_INCREMENT,
  `caption` VARCHAR(255) NULL,
  `image_filename` VARCHAR(45) NULL,
  `num_likes` INT NULL,
  PRIMARY KEY (`gallery_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanaytourism`.`page_content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tanaytourism`.`page_content` ;

CREATE TABLE IF NOT EXISTS `tanaytourism`.`page_content` (
  `content_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `slug` VARCHAR(100) NULL,
  `content` TEXT NULL,
  `isShown` INT NULL,
  `page_page_id` INT NOT NULL,
  `gallery_gallery_id` INT NOT NULL,
  `users_user_id` INT NOT NULL,
  PRIMARY KEY (`content_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanaytourism`.`page_click`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tanaytourism`.`page_click` ;

CREATE TABLE IF NOT EXISTS `tanaytourism`.`page_click` (
  `click_id` INT NOT NULL AUTO_INCREMENT,
  `num_clicks` INT NULL,
  `date` DATETIME NULL,
  `page_page_id` INT NOT NULL,
  PRIMARY KEY (`click_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanaytourism`.`news_clicks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tanaytourism`.`news_clicks` ;

CREATE TABLE IF NOT EXISTS `tanaytourism`.`news_clicks` (
  `click_id` INT NOT NULL AUTO_INCREMENT,
  `num_clicks` INT NULL,
  `date` DATETIME NULL,
  `news_news_id` INT NOT NULL,
  PRIMARY KEY (`click_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanaytourism`.`hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tanaytourism`.`hotel` ;

CREATE TABLE IF NOT EXISTS `tanaytourism`.`hotel` (
  `hotel_id` INT NOT NULL AUTO_INCREMENT,
  `hotel_name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`hotel_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanaytourism`.`amenities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tanaytourism`.`amenities` ;

CREATE TABLE IF NOT EXISTS `tanaytourism`.`amenities` (
  `amenity_id` INT NOT NULL AUTO_INCREMENT,
  `amenity_name` VARCHAR(45) NULL,
  `amenity_imagefile` VARCHAR(45) NULL,
  `hotel_hotel_id` INT NOT NULL,
  PRIMARY KEY (`amenity_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanaytourism`.`hotel_room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tanaytourism`.`hotel_room` ;

CREATE TABLE IF NOT EXISTS `tanaytourism`.`hotel_room` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `room_name` VARCHAR(45) NULL,
  `capacity` INT(2) NULL,
  `price` DECIMAL(6,2) NULL,
  `room_image` VARCHAR(45) NULL,
  `hotel_hotel_id` INT NOT NULL,
  PRIMARY KEY (`room_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanaytourism`.`metric`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tanaytourism`.`metric` ;

CREATE TABLE IF NOT EXISTS `tanaytourism`.`metric` (
  `metric_id` INT NOT NULL AUTO_INCREMENT,
  `metric_name` VARCHAR(45) NULL,
  `formula` VARCHAR(45) NULL,
  PRIMARY KEY (`metric_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanaytourism`.`hotel_metric`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tanaytourism`.`hotel_metric` ;

CREATE TABLE IF NOT EXISTS `tanaytourism`.`hotel_metric` (
  `hotelmetric_id` INT NOT NULL AUTO_INCREMENT,
  `variable1` DECIMAL(6,2) NULL,
  `variable2` DECIMAL(6,2) NULL,
  `result` DECIMAL(6,2) NULL,
  `date_computed` DATETIME NULL,
  `hotel_hotel_id` INT NOT NULL,
  `metric_metric_id` INT NOT NULL,
  PRIMARY KEY (`hotelmetric_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanaytourism`.`activity_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tanaytourism`.`activity_logs` ;

CREATE TABLE IF NOT EXISTS `tanaytourism`.`activity_logs` (
  `activity_id` INT NOT NULL AUTO_INCREMENT,
  `activity_description` VARCHAR(45) NULL,
  `table_affected` VARCHAR(45) NULL,
  `date_logged` DATETIME NULL,
  `users_user_id` INT NOT NULL,
  PRIMARY KEY (`activity_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanaytourism`.`activity_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tanaytourism`.`activity_type` ;

CREATE TABLE IF NOT EXISTS `tanaytourism`.`activity_type` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NULL,
  `activity_logs_activity_id` INT NOT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
